### ISSUE TITLE
Feature request: lossy_transparent option

### ISSUE THREAD

**Issue by lisamai** [imagemin/imagemin-zopfli#2]
Not sure what the procedure is, so feel free to close if this isn't the right process.

Would it be possible to add lossy_transparent to the options available to pass on to zopfli (pass on as --lossy_transparent)? Or would it be better to just submit a pull request with the option?

Thanks!

**Comment by shinnn** [comment]
Fixed in https://github.com/imagemin/imagemin-zopfli/commit/89281f483467374813f5b82d8dc7c5a142a61bc8.
